var mongoose 			= require('mongoose'),
 	Schema 				= mongoose.Schema;

var Palette = new Schema ({
	uuid 			: String,
	artistID 		: String,
	title 			: String,
	description 	: String,
	tags 			: String,
	colors 			: Array,
	tools 			: Array,
	weights 		: Array,
	brushSizes 		: Array,
	combinations 	: Array,
	autoGenerated 	: Boolean,
	created 		: Date,
	updated 		: Date
});

module.exports = mongoose.model("Palette", Palette);
